Explicitly type-cast pg_lsn to text (postgresql plugin)
This fixes the following error on postgresql-9.4:

```
ERROR:  function split_part(pg_lsn, unknown, integer) does not exist
LINE 3:         ('x' || lpad(split_part(sent_location,   '/', 1), 8,...
                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type
casts.
```